export const skillData: [id: number, en: string, ja: string][] = [
  [1, "Attack Boost", "攻撃"],
  [2, "Agitator", "挑戦者"],
  [3, "Peak Performance", "フルチャージ"],
  [4, "Resentment", "逆恨み"],
  [5, "Resuscitate", "死中に活"],
  [6, "Critical Eye", "見切り"],
  [7, "Critical Boost", "超会心"],
  [8, "Weakness Exploit", "弱点特効"],
  [9, "Latent Power", "力の解放"],
  [10, "Maximum Might", "渾身"],
  [11, "Critical Element", "会心撃【属性】"],
  [12, "Master's Touch", "達人芸"],
  [13, "Fire Attack", "火属性攻撃強化"],
  [14, "Water Attack", "水属性攻撃強化"],
  [15, "Ice Attack", "氷属性攻撃強化"],
  [16, "Thunder Attack", "雷属性攻撃強化"],
  [17, "Dragon Attack", "龍属性攻撃強化"],
  [18, "Poison Attack", "毒属性強化"],
  [19, "Paralysis Attack", "麻痺属性強化"],
  [20, "Sleep Attack", "睡眠属性強化"],
  [21, "Blast Attack", "爆破属性強化"],
  [22, "Handicraft", "匠"],
  [23, "Razor Sharp", "業物"],
  [24, "Spare Shot", "弾丸節約"],
  [25, "Protective Polish", "剛刃研磨"],
  [26, "Mind's Eye", "心眼"],
  [27, "Ballistics", "弾導強化"],
  [28, "Bludgeoner", "鈍器使い"],
  [29, "Bow Charge Plus", "弓溜め段階解放"],
  [30, "Focus", "集中"],
  [31, "Power Prolonger", "強化持続"],
  [32, "Marathon Runner", "ランナー"],
  [33, "Constitution", "体術"],
  [34, "Stamina Surge", "スタミナ急速回復"],
  [35, "Guard", "ガード性能"],
  [36, "Guard Up", "ガード強化"],
  [37, "Offensive Guard", "攻めの守勢"],
  [38, "Critical Draw", "抜刀術【技】"],
  [39, "Punishing Draw", "抜刀術【力】"],
  [40, "Quick Sheathe", "納刀術"],
  [41, "Slugger", "ＫＯ術"],
  [42, "Stamina Thief", "スタミナ奪取"],
  [43, "Affinity Sliding", "滑走強化"],
  [44, "Horn Maestro", "笛吹き名人"],
  [45, "Artillery", "砲術"],
  [46, "Load Shells", "砲弾装填"],
  [47, "Special Ammo Boost", "特殊射撃強化"],
  [48, "Normal/Rapid Up", "通常弾・連射矢強化"],
  [49, "Pierce Up", "貫通弾・貫通矢強化"],
  [50, "Spread Up", "散弾・拡散矢強化"],
  [51, "Ammo Up", "装填拡張"],
  [52, "Reload Speed", "装填速度"],
  [53, "Recoil Down", "反動軽減"],
  [54, "Steadiness", "ブレ抑制"],
  [55, "Rapid Fire Up", "速射強化"],
  [56, "Defense Boost", "防御"],
  [57, "Divine Blessing", "精霊の加護"],
  [58, "Recovery Up", "体力回復量ＵＰ"],
  [59, "Recovery Speed", "回復速度"],
  [60, "Speed Eating", "早食い"],
  [61, "Earplugs", "耳栓"],
  [62, "Windproof", "風圧耐性"],
  [63, "Tremor Resistance", "耐震"],
  [64, "Bubbly Dance", "泡沫の舞"],
  [65, "Evade Window", "回避性能"],
  [66, "Evade Extender", "回避距離ＵＰ"],
  [67, "Fire Resistance", "火耐性"],
  [68, "Water Resistance", "水耐性"],
  [69, "Ice Resistance", "氷耐性"],
  [70, "Thunder Resistance", "雷耐性"],
  [71, "Dragon Resistance", "龍耐性"],
  [72, "Blight Resistance", "属性やられ耐性"],
  [73, "Poison Resistance", "毒耐性"],
  [74, "Paralysis Resistance", "麻痺耐性"],
  [75, "Sleep Resistance", "睡眠耐性"],
  [76, "Stun Resistance", "気絶耐性"],
  [77, "Muck Resistance", "泥雪耐性"],
  [78, "Blast Resistance", "爆破やられ耐性"],
  [79, "Botanist", "植生学"],
  [80, "Geologist", "地質学"],
  [81, "Partbreaker", "破壊王"],
  [82, "Capture Master", "捕獲名人"],
  [83, "Carving Master", "剥ぎ取り名人"],
  [84, "Good Luck", "幸運"],
  [85, "Speed Sharpening", "砥石使用高速化"],
  [86, "Bombardier", "ボマー"],
  [87, "Mushroomancer", "キノコ大好き"],
  [88, "Item Prolonger", "アイテム使用強化"],
  [89, "Wide-Range", "広域化"],
  [90, "Free Meal", "満足感"],
  [91, "Heroics", "火事場力"],
  [92, "Fortify", "不屈"],
  [93, "Flinch Free", "ひるみ軽減"],
  [94, "Jump Master", "ジャンプ鉄人"],
  [95, "Carving Pro", "剥ぎ取り鉄人"],
  [96, "Hunger Resistance", "腹減り耐性"],
  [97, "Leap of Faith", "飛び込み"],
  [98, "Diversion", "陽動"],
  [99, "Master Mounter", "乗り名人"],
  [100, "Chameleos Blessing", "霞皮の恩恵"],
  [101, "Kushala Blessing", "鋼殻の恩恵"],
  [102, "Teostra Blessing", "炎鱗の恩恵"],
  [103, "Dragonheart", "龍気活性"],
  [104, "Wirebug Whisperer", "翔蟲使い"],
  [105, "Wall Runner", "壁面移動"],
  [106, "Counterstrike", "逆襲"],
  [107, "Rapid Morph", "高速変形"],
  [108, "Hellfire Cloak", "鬼火纏"],
  [109, "Wind Alignment", "風紋の一致"],
  [110, "Thunder Alignment", "雷紋の一致"],
  [111, "Stormsoul", "風雷合一"],
  [112, "Blood Rite", "血氣"],
  [113, "Dereliction", "伏魔響命"],
  [114, "Furious", "激昂"],
  [115, "Mail of Hellfire", "業鎧【修羅】"],
  [116, "Coalescence", "災禍転福"],
  [117, "Bloodlust", "狂竜症【蝕】"],
  [122, "Redirection", "合気"],
  [123, "Spiribird's Call", "供応"],
  [124, "Charge Master", "チャージマスター"],
  [125, "Foray", "攻勢"],
  [126, "Tune-Up", "チューンアップ"],
  [127, "Grinder (S)", "研磨術【鋭】"],
  [128, "Bladescale Hone", "刃鱗磨き"],
  [129, "Wall Runner (Boost)", "壁面移動【翔】"],
  [131, "Chain Crit", "連撃"],
  [133, "Quick Breath", "疾之息吹"],
];
